version: 18.3.1.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\7z
image: Visual Studio 2017
platform: x64
configuration: Release
build:
    parallel: true
    project: CubeIce7z.sln
    publish_nuget: true
    verbosity: normal
after_build:
    - copy /Y Release\x64\7z.dll 7z.dll
    - copy /Y Release\x64\7z.sfx 7z.sfx
artifacts:
    - path: 7z.dll
      type: file
    - path: 7z.sfx
      type: file