version: 19.0.1.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\7z
image: Visual Studio 2017
platform:
    - Win32
    - x64
configuration: Release
build:
    parallel: true
    project: Cube.Native.SevenZip.sln
    publish_nuget: true
    verbosity: minimal
after_build:
    - copy /Y Release\%PLATFORM%\7z.dll 7z.dll
    - copy /Y Release\%PLATFORM%\7z.sfx 7z.sfx
    - 7z a 7z-%PLATFORM%.zip 7z.dll 7z.sfx
artifacts:
    - path: 7z-%PLATFORM%.zip
