version: 0.8.0.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\7z
image: Visual Studio 2017
platform: Win32
configuration: Release
build: 
    parallel: true
    project: CubeIce7z.sln
    publish_nuget: true
    verbosity: normal
after_build:
    - copy /Y Release\Win32\7z.dll 7z.dll
    - copy /Y Release\Win32\7z.sfx 7z.sfx
artifacts:
    - path: 7z.dll
      type: file
    - path: 7z.sfx
      type: file